apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-utils
  namespace: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-utils
  template:
    metadata:
      labels:
        app: dns-utils
    spec:
      containers:
        - name: dns-utils
          image: nicolaka/netshoot:latest
          command: ["sleep", "infinity"]
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"